### ISSUE TITLE
Create a production GCR project for server side docker images

### ISSUE THREAD

**Issue by jackgr** [kubernetes/deployment-manager#259]
Currently, we use dm-k8s-testing. It has both the wrong name, since we're now called helm, and the wrong implications, since it's to be used for production, not testing.

**Comment by jackgr** [comment]
Done. See dm-k8s-prod.

**Comment by vaikas-google** [comment]
Isn't the name still wrong though? The implication you had was the name should not contain dm, but something like helm. Is there another bug tracking that, or is this just a temporary change?

**Comment by jackgr** [comment]
This is the production gcr repo for the final DM binaries. Going forward, we'll need a new repo with helm in the name.
